#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_CAM_CAL_S5K5E2FROTP_SUPPORT)	+= s5k5e2frotp.o
#obj-y	+= s5k5e2otp.o
